[tool.poetry]
name = "prediction-market-agent"
version = "0.1.0"
description = ""
authors = ["Gnosis"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
python-dotenv = "*"
openai = "*"
langchain = "~0.1.1"
langchain-experimental = "*"
langchain-community = "*"
langchain-openai = "*"
numexpr = "*"
pyautogen = "*"
beautifulsoup4 = "*"
serpapi = "*"
google-search-results = "*"
pytest = "*"
llama-index = "~0.9.0"
duckduckgo-search = "*"
crewai = "*"
# metagpt = "*" # Commented out because requires super old version of langchain, and conflicts with crewai.

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
