[tool.poetry]
name = "prediction-market-agent"
version = "0.1.0"
description = ""
authors = ["Gnosis"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
python-dotenv = "*"
openai = "*"
langchain = "*"
langchain-experimental = "*"
numexpr = "*"
pyautogen = "*"
beautifulsoup4 = "*"
serpapi = "*"
google-search-results = "*"
pytest = "*"
llama-index = "~0.9.0"
metagpt = "*"
duckduckgo-search = "*"
# crewai = "*"  # Conflicts with metagpt due to langchain, commented out as metagpt seems to have bigger traction, install manually in the environment for usage.

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
