name: Python CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python_prepare
      - name: Run mypy
        run: poetry run mypy

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python_prepare
      - name: Run pytest
        env:
          MANIFOLD_API_KEY: ${{ secrets.MANIFOLD_API_KEY }}
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BET_FROM_ADDRESS: ${{ secrets.BET_FROM_ADDRESS }}
          BET_FROM_PRIVATE_KEY: ${{ secrets.BET_FROM_PRIVATE_KEY }}
        shell: bash
        run: poetry run pytest

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python_prepare
      - name: Check with black
        run: poetry run black --check .
